using System.Text;
using System.Web.Mvc;

namespace Frontend.Action
{
    public class MyControllerActionInvoker: IActionInvoker
    {
        public bool InvokeAction(ControllerContext controllerContext, string actionName)
        {
            var view = new StringBuilder();
            view.Append("<div>");
            view.Append("Content generated by my custom controller action invoker");
            view.Append("</div>");
            controllerContext.HttpContext.Response.Write(view.ToString());
            return true;
        }
    }
}